import { useMemo, useState } from "react";
import { bookmarkletSource } from "../bookmarklet-source";
import { ArrowRight, BookOpen, Brackets, Check, ChevronDown, Clipboard, Code2, Copy, ExternalLink, Github, Monitor, MousePointer2, ShieldCheck, Smartphone, Sparkles, TerminalSquare, X } from "lucide-react";

const features = [
  { icon: TerminalSquare, title: "Console", body: "ログ、警告、エラーを確認。JavaScriptの実行、履歴、Autocompleteにも対応。" },
  { icon: MousePointer2, title: "Element", body: "要素を選択してDOMを確認・編集。タッチ操作でも使えるセレクター。" },
  { icon: Brackets, title: "Web Network", body: "Fetch / XHR / WebSocketを監視し、ヘッダーやレスポンスを確認。" },
  { icon: Code2, title: "Sources", body: "ページのHTML・CSS・JavaScriptを一覧表示し、ソースを確認。" },
];

function makeBookmarklet() { return `javascript:(function(){${bookmarkletSource}
})();`; }
async function copyText(value: string) { try { await navigator.clipboard.writeText(value); return true; } catch { const area = document.createElement("textarea"); area.value=value; area.style.position="fixed"; area.style.opacity="0"; document.body.appendChild(area); area.select(); const copied=document.execCommand("copy"); area.remove(); return copied; } }

export default function Home() {
  const [device, setDevice] = useState<"mac" | "mobile">("mac");
  const [copied, setCopied] = useState(false);
  const [showCode, setShowCode] = useState(false);
  const [running, setRunning] = useState(false);
  const origin = typeof window === "undefined" ? "https://safarbmklt-ap3sy5ke.manus.space" : window.location.origin;
  const bookmarklet = useMemo(() => makeBookmarklet(), []);
  const handleCopy = async () => { if (await copyText(bookmarklet)) { setCopied(true); window.setTimeout(() => setCopied(false), 1800); } };
  const runHere = () => { if (running) { window.location.reload(); return; } const script=document.createElement("script"); script.id="__bookmarklet_devtools__"; script.src=new URL("bookmarklet-devtools-v136b3f0.js", document.baseURI).href; script.onload=()=>setRunning(true); script.onerror=()=>alert("DevTools本体の読み込みに失敗しました"); document.head.appendChild(script); };
  const pickWebElement = () => {
    const old = document.getElementById("__web_element_picker__");
    if (old) { old.remove(); return; }
    const overlay = document.createElement("div");
    overlay.id = "__web_element_picker__";
    overlay.innerHTML = '<div class="web-picker-box"><strong>Web Element Picker</strong><button aria-label="close">×</button><div class="web-picker-value">ページ上の要素にカーソルを合わせてクリック</div></div><div class="web-picker-outline"></div>';
    document.body.appendChild(overlay);
    const outline = overlay.querySelector(".web-picker-outline") as HTMLDivElement;
    const value = overlay.querySelector(".web-picker-value") as HTMLDivElement;
    const close = overlay.querySelector("button") as HTMLButtonElement;
    const selector = (el: Element) => el.id ? `#${el.id}` : el.tagName.toLowerCase() + Array.from(el.classList).filter(Boolean).slice(0,2).map(c => `.${c}`).join("");
    const move = (event: MouseEvent) => { const el = document.elementFromPoint(event.clientX, event.clientY); if (!el || overlay.contains(el)) return; const r = el.getBoundingClientRect(); outline.style.cssText = `display:block;left:${r.left + scrollX}px;top:${r.top + scrollY}px;width:${r.width}px;height:${r.height}px;`; value.textContent = `${el.tagName.toLowerCase()}  ${selector(el)}`; };
    const pick = (event: MouseEvent) => { const el = document.elementFromPoint(event.clientX, event.clientY); if (!el || overlay.contains(el)) return; event.preventDefault(); event.stopPropagation(); value.textContent = `${el.tagName.toLowerCase()}  ${selector(el)}  — selected`; };
    close.onclick = () => overlay.remove(); document.addEventListener("mousemove", move, true); document.addEventListener("click", pick, true);
  };

  return <div className="site-shell">
    <header className="topbar"><a className="brand" href="#top"><span className="brand-mark"><TerminalSquare size={17} /></span><span>Safari<span className="brand-muted">/</span>DevTools</span></a><nav className="topnav"><a href="#features">Features</a><a href="#install">Install</a><a href="#notes">Notes</a><a className="github-link" href="https://github.com/DeveloperExotic/Bookmarklet-Dev-Tools" target="_blank" rel="noreferrer"><Github size={15} /> Source</a></nav></header>
    <main id="top">
      <section className="hero section-wrap"><div className="hero-copy"><div className="eyebrow"><span className="eyebrow-dot" /> BOOKMARKLET DEVTOOLS / SAFARI</div><h1>Safariに、<br /><em>開発者ツール</em>を。</h1><p className="hero-lede">ブックマークを1回タップするだけ。ページを離れずに、Console・Element・Web Networkを確認できる軽量DevTools。</p><div className="hero-actions"><a className="primary-cta" href="#install">インストールする <ArrowRight size={17} /></a><button className="secondary-cta demo-cta" onClick={runHere}>{running ? "DevToolsを閉じる" : "このページで試す"}</button></div><div className="hero-meta"><ShieldCheck size={15} /> 外部CDNなし・このサイトから自己ホスト配布</div></div><div className="hero-visual"><div className="grid-glow" /><div className="terminal-card"><div className="terminal-head"><span className="traffic red" /><span className="traffic yellow" /><span className="traffic green" /><span className="terminal-title">console — safari.devtools</span><span className="terminal-dots">•••</span></div><div className="terminal-tabs"><span className="active">Console</span><span>Element</span><span>Web Network</span><span>Sources</span></div><div className="terminal-body"><div className="code-line dim"><span>01</span><b>// page inspection ready</b></div><div className="code-line"><span>02</span><i>const</i> page = <strong>document</strong>.body;</div><div className="code-line"><span>03</span><i>console</i>.log(<mark>page</mark>);</div><div className="code-line result"><span>04</span><small>▸</small> &lt;body class="app"&gt; …</div><div className="code-line"><span>05</span><em className="cursor">▋</em></div></div><div className="terminal-status"><span><span className="status-dot" /> ready</span><span>Safari · JS</span></div></div><div className="float-chip chip-one"><Sparkles size={14} /> live inspection</div><div className="float-chip chip-two"><span className="mini-bars"><b /><b /><b /><b /></span> web network 24</div></div></section>
      <section className="trust-strip"><div className="section-wrap trust-inner"><span>BUILT FOR QUICK CHECKS</span><i /><span>MAC · IPHONE · IPAD</span><i /><span>NO EXTENSION REQUIRED</span></div></section>
      <section className="section-wrap feature-section" id="features"><div className="section-kicker">01 / WHAT YOU GET</div><div className="section-heading-row"><h2>小さく起動して、<br /><span>大きく調べる。</span></h2><p>Safariの本物のWeb Inspectorを置き換えるものではなく、ページ上に必要な観測道具をすぐ呼び出すためのBookmarklet DevToolsです。</p></div><div className="feature-grid">{features.map(({icon:Icon,title,body},index)=><article className="feature-card" key={title}><div className="feature-index">0{index+1}</div><div className="feature-icon"><Icon size={20} /></div><h3>{title}</h3><p>{body}</p><span className="feature-arrow"><ArrowRight size={16} /></span></article>)}</div></section>
      <section className="install-section" id="install"><div className="section-wrap install-grid"><div className="install-intro"><div className="section-kicker light">02 / INSTALL IN SECONDS</div><h2>登録は、<br /><span>2ステップ。</span></h2><p>まず下のボタンでこのページ上のDevToolsを試せます。Safariへ登録する場合はURLをコピーします。</p><div className="safe-note"><ShieldCheck size={17} /><span><strong>自己ホスト配布</strong><br />スクリプトはこのサイトの同一オリジンから配信されます。</span></div></div><div className="install-panel"><div className="web-installer"><div><span className="live-pill"><span /> WEB INSTALLER</span><h3>このページで今すぐ試す</h3><p>Safariのブックマーク登録前に、DevToolsのボタン操作を確認できます。</p></div><div className="web-installer-actions"><button type="button" className="run-button" onClick={runHere}>{running ? <><X size={16} /> 閉じる</> : <><TerminalSquare size={16} /> 起動する</>}</button><button type="button" className="picker-button" onClick={pickWebElement}><MousePointer2 size={16} /> Web要素を選択</button></div></div><div className="device-tabs" role="tablist"><button className={device === "mac" ? "selected" : ""} onClick={() => setDevice("mac")}><Monitor size={16} /> Mac Safari</button><button className={device === "mobile" ? "selected" : ""} onClick={() => setDevice("mobile")}><Smartphone size={16} /> iPhone / iPad</button></div><div className="install-steps"><div className="step"><span className="step-no">01</span><div><h3>Bookmarklet URLを取得</h3><button type="button" className="bookmarklet-link" onClick={() => void handleCopy()}><Clipboard size={16} /> {copied ? "コピーしました" : "URLをコピー"}</button><a className="drag-bookmarklet" href={bookmarklet} draggable="true">Mac: このリンクをブックマークバーへドラッグ</a><p>{device === "mac" ? "ボタンでURLをコピーするか、下のリンクをブックマークバーへドラッグ。" : "コピーしたURLをブックマークのURL欄へ貼り付けます。"}</p></div></div><div className="step"><span className="step-no">02</span><div><h3>保存して、任意のページで起動</h3><p>{device === "mac" ? "ブックマークを保存し、調べたいページでクリックします。" : "ブックマークを編集し、URL欄へ貼り付けて保存します。"}</p></div></div></div><div className="code-box"><div className="code-box-head"><span>BOOKMARKLET URL</span><button onClick={handleCopy}>{copied ? <><Check size={14} /> Copied</> : <><Copy size={14} /> Copy</>}</button></div><code>{bookmarklet}</code></div><button className="show-code" onClick={() => setShowCode(!showCode)}>{showCode ? <X size={15} /> : <ChevronDown size={15} />} {showCode ? "コードを閉じる" : "コードを表示"}</button>{showCode && <pre className="raw-code">{bookmarklet}</pre>}</div></div></section>
      <section className="section-wrap notes-section" id="notes"><div className="section-kicker">03 / GOOD TO KNOW</div><div className="notes-grid"><div><h2>できること、<br /><span>できないこと。</span></h2><p className="notes-lede">これはページに挿入される開発補助ツールです。Safari本体のネイティブWeb Inspectorを自動で開くものではありません。</p></div><div className="note-list"><div className="note-item"><Check size={17} /><div><strong>使える</strong><p>Console、Elementの確認・編集、Web Networkの観測、ソース表示、Cookie確認。</p></div></div><div className="note-item"><X size={17} /><div><strong>対象外</strong><p>SafariのDevelopメニュー、ネイティブWeb Inspector、ブレークポイントの完全なデバッグ。</p></div></div><div className="note-item"><ShieldCheck size={17} /><div><strong>安全に使う</strong><p>JavaScriptを実行するため、信頼できるページでのみ使い、ソースを確認してから登録してください。</p></div></div></div></div></section><section className="final-cta section-wrap"><div><div className="section-kicker">READY WHEN YOU ARE</div><h2>まずは、1ページで<br /><span>試してみる。</span></h2></div><a className="primary-cta dark-cta" href="#install">Install DevTools <ArrowRight size={17} /></a></section>
    </main><footer className="footer section-wrap"><div className="brand"><span className="brand-mark"><TerminalSquare size={16} /></span><span>Safari<span className="brand-muted">/</span>DevTools</span></div><div className="footer-links"><a href="/bookmarklet-devtools.js"><Code2 size={14} /> script.js</a><a href="https://github.com/DeveloperExotic/Bookmarklet-Dev-Tools" target="_blank" rel="noreferrer"><ExternalLink size={14} /> source repository</a></div><span className="footer-copy">© 2026 · Bookmarklet DevTools</span></footer>
  </div>;
}
